# This notebook is to build deep neural network (forward & backward) propagation using python only from Gokking deep learning Book

In [13]:
import numpy as np 
np.random.seed(1)
def relu(x):
    return (x>0) * x
def relu2drev(output): 
    return output>0


alpha = 0.2
hiden_size = 4
streetlight = np.array([[1,0,1],
[0,1,1],
[0,0,1],
[1,1,1]])

walk_vs_stop=np.array([[1,1,0,0]]).T

weight_0_1 = 2*np.random.random((3,hiden_size))-1
weight_1_2 = 2*np.random.random((hiden_size,1))-1

for i in range(60):
    #the total error for the final network 
    layer_2_error =0
    for i in range(len(streetlight)):
        # all of the following is the forward propogation
        layer_0 = streetlight[i:i+1]
        layer_1 = relu(np.dot(layer_0 ,weight_0_1))
        layer_2 = np.dot(layer_1,weight_1_2)
        # know the total error of this stage 
        layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1])**2)

        # start the backpropagation of the network
        layer_2_delta = (layer_2 - walk_vs_stop[i:i+1])
        #thsi step for destroy the neuron who is negative or zero 
        layer_1_delta = layer_2_delta.dot(weight_1_2.T)*relu2drev(layer_1)


        #change the wieghts
        weight_0_1 -= alpha *layer_1.T.dot(layer_2_delta)
        weight_1_2 -= alpha*layer_0.T.dot(layer_1_delta)
    if(i % 10 ==9):
        print("error:"+str(layer_2_error))

ValueError: operands could not be broadcast together with shapes (3,4) (4,1) (3,4) 

In [6]:
import numpy as np 
np.random.seed(1)
def relu(x):
    return (x>0) * x
def relu2drev(output): 
    return output>0


alpha = 0.2
hiden_size = 4
streetlight = np.array([[1,0,1],
[0,1,1],
[0,0,1],
[1,1,1]])

walk_vs_stop=np.array([[1,1,0,0]]).T

weight_0_1 = 2*np.random.random((3,hiden_size))-1
weight_1_2 = 2*np.random.random((hiden_size,1))-1

# forward propogation 
for iterations in range(60):
    layer_2_error = 0
    for i in range(len(streetlight)):
        layer_0 = streetlight[i:i+1]
        layer_1 = relu(np.dot(layer_0,weight_0_1))
        layer_2 = np.dot(layer_1,weight_1_2)

        layer_2_error+= np.sum((layer_2 -walk_vs_stop[i:i+1])**2)

        # back propogation
        layer_2_delta = (layer_2-walk_vs_stop[i:i+1])

        layer_1_delta = layer_2_delta.dot(weight_1_2.T)*relu(layer_1)
        # print(layer_1_delta)
        # print("############################")
        # get the wieghted delta 
        wight_delta_1_2 = layer_1.T.dot(layer_2_delta)
        wieght_delta_0_1 = layer_0.T.dot(layer_1_delta)

        #change the weights 
        weight_1_2 -= wight_delta_1_2 * alpha
        weight_0_1 -= wieght_delta_0_1 * alpha
    if (iterations %10 ==9):
        print("error" + str(layer_2_error))

error1.1046765522435662
error1.0675201719779754
error1.0400690043885754
error0.9874195056409882
error0.7730093094114814
error0.5629341183365232


In [2]:
import numpy as np
test = np.random.random((3,4))
print(test)


[[0.59471828 0.20391504 0.64004479 0.07218429]
 [0.09231634 0.40434902 0.51861437 0.15645694]
 [0.44764939 0.06359552 0.70496686 0.57844511]]


In [3]:
print(test-1)

[[-0.40528172 -0.79608496 -0.35995521 -0.92781571]
 [-0.90768366 -0.59565098 -0.48138563 -0.84354306]
 [-0.55235061 -0.93640448 -0.29503314 -0.42155489]]


In [8]:
print(streetlight[0:1])

[[1 0 1]]


In [9]:
print(streetlight[1:2
])

[[0 1 1]]
